/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hr.algebra;

import hr.algebra.model.User;
import hr.algebra.view.DeleteDatabaseAndUploadRssParse;
import hr.algebra.view.UploadGenreActorDirector;
import hr.algebra.view.UploadMovie;

/**
 *
 * @author windsten
 */
public class MovieArticle extends javax.swing.JFrame {
    
    private User loggedInUser;
    /**
     * Creates new form MovieArticle
     */
    public MovieArticle(User user) {
        this.loggedInUser = user;
        
        initComponents();
        initPanels();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpContent = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpContent, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpContent, javax.swing.GroupLayout.DEFAULT_SIZE, 658, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane tpContent;
    // End of variables declaration//GEN-END:variables

    private static final String UPLOAD_MOVIE = "Upload movie";
    private static final String UPLOAD_ACTORDIRECTORGENRE = "Upload Actor, Genre and Directors";
    private static final String ADMIN_CONTROLS = "Admin controls";
    
    
    private void initPanels() {
        if ("User".equalsIgnoreCase(loggedInUser.getRoleName())) {
            tpContent.add(UPLOAD_MOVIE, new UploadMovie());
            tpContent.add(UPLOAD_ACTORDIRECTORGENRE, new UploadGenreActorDirector());
        }
        if ("Admin".equalsIgnoreCase(loggedInUser.getRoleName())) {
            tpContent.add(UPLOAD_MOVIE, new UploadMovie());
            tpContent.add(UPLOAD_ACTORDIRECTORGENRE, new UploadGenreActorDirector());
            tpContent.add(ADMIN_CONTROLS, new DeleteDatabaseAndUploadRssParse());
        }
        
        
    }

}
