/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package hr.algebra.view;

import static hr.algebra.LoginRegisterForm.loggedInUser;
import hr.algebra.MovieArticle;
import hr.algebra.dal.RepoFactory;
import hr.algebra.dal.Repository;
import hr.algebra.utilities.MessageUtils;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author windsten
 */
public class DeleteDatabaseAndUploadRssParse extends javax.swing.JPanel {

    private Repository repository;
    
    /**
     * Creates new form DeleteDatabaseAndUploadRssParse
     */
    public DeleteDatabaseAndUploadRssParse() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnWipeEverythingMovieDatabase = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfRssUrl = new javax.swing.JTextField();

        btnWipeEverythingMovieDatabase.setBackground(new java.awt.Color(255, 0, 0));
        btnWipeEverythingMovieDatabase.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnWipeEverythingMovieDatabase.setForeground(new java.awt.Color(255, 255, 255));
        btnWipeEverythingMovieDatabase.setText("WIPE MOVIE!! EVERYTHING!!!");
        btnWipeEverythingMovieDatabase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWipeEverythingMovieDatabaseActionPerformed(evt);
            }
        });

        jLabel1.setText("RSS Import to Movie Database");
        jLabel1.setEnabled(false);

        jLabel2.setText("URL");
        jLabel2.setEnabled(false);

        tfRssUrl.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfRssUrl, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addComponent(btnWipeEverythingMovieDatabase))
                .addContainerGap(389, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(btnWipeEverythingMovieDatabase, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(jLabel1)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfRssUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(340, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnWipeEverythingMovieDatabaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWipeEverythingMovieDatabaseActionPerformed
        try{
            repository.DeleteAllDataExceptUsers();
            JOptionPane.showMessageDialog(null, "The database was wiped (except users)");
            
            MovieArticle movieArticle = new MovieArticle(loggedInUser);
            movieArticle.setVisible(true);
            
            SwingUtilities.windowForComponent(this).dispose();
        }   catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null,"An unexpected error occurred!\n" + e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnWipeEverythingMovieDatabaseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnWipeEverythingMovieDatabase;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField tfRssUrl;
    // End of variables declaration//GEN-END:variables

    private void init() {
        try {
            initValidation();
            initRepository();
        } catch (Exception ex) {
            MessageUtils.showErrorMessage("Unrecoverable error", "Cannot initiate the form");
            System.exit(1);
        }
    }

    private void initValidation() {
        return;
    }
    
    private void initRepository() throws Exception {
        repository = RepoFactory.getRepository();
    }
}
