/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package hr.algebra.view;

import hr.algebra.dal.RepoFactory;
import hr.algebra.dal.Repository;
import hr.algebra.model.Actor;
import hr.algebra.model.Director;
import hr.algebra.model.Genre;
import hr.algebra.model.Movie;
import hr.algebra.utilities.FileUtils;
import hr.algebra.utilities.IconUtils;
import hr.algebra.utilities.MessageUtils;
import hr.algebra.view.model.list.ActorListModel;
import hr.algebra.view.model.list.DirectorListModel;
import hr.algebra.view.model.list.GenreListModel;
import hr.algebra.view.model.table.MovieTableModel;
import hr.algebra.view.model.transfer.ActorExportTransferHandler;
import hr.algebra.view.model.transfer.DirectorExportTransferHandler;
import hr.algebra.view.model.transfer.GenreExportTransferHandler;
import hr.algebra.view.model.transfer.MultiEntityTransferHandler;
import java.awt.Component;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.time.LocalDate;
import java.util.Arrays;
import java.util.List;
import java.util.Optional;
import java.util.Set;
import java.util.UUID;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Collectors;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.text.JTextComponent;


/**
 *
 * @author windsten
 */
public class UploadMovie extends javax.swing.JPanel {

    private List<JTextComponent> validationFields;
    private List<JLabel> errorLabels;
    
    private Repository repository;
    
    private Movie selectedMovie;
    private MovieTableModel MovieModel;
    
    
    private ActorListModel ActorModel;
    private DirectorListModel DirectorModel;
    private GenreListModel GenreModel;

    
    /**
     * Creates new form UploadMovie
     */
    public UploadMovie() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbMovies = new javax.swing.JTable();
        tfPicturePath = new javax.swing.JTextField();
        btnChoose = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        lbDateError = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbDescError = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfTitle = new javax.swing.JTextField();
        lbTitleError = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfDate = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        lbIcon = new javax.swing.JLabel();
        lbPicturePathError = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        listActor = new javax.swing.JList<>();
        jScrollPane7 = new javax.swing.JScrollPane();
        listDirector = new javax.swing.JList<>();
        jScrollPane8 = new javax.swing.JScrollPane();
        listGenre = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        taDesc = new javax.swing.JTextPane();
        jToolBarSelectedActorDirectorGenre = new javax.swing.JToolBar();

        jLabel1.setText("Actor");

        jLabel2.setText("Director");

        jLabel3.setText("Genre");

        tbMovies.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbMovies.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbMoviesMouseClicked(evt);
            }
        });
        tbMovies.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbMoviesKeyReleased(evt);
            }
        });
        jScrollPane4.setViewportView(tbMovies);

        tfPicturePath.setEditable(false);

        btnChoose.setText("Choose");
        btnChoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseActionPerformed(evt);
            }
        });

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(255, 0, 51));
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        lbDateError.setForeground(new java.awt.Color(255, 0, 51));
        lbDateError.setText("X");

        jLabel6.setText("Description");

        lbDescError.setForeground(new java.awt.Color(255, 0, 51));
        lbDescError.setText("X");

        jLabel4.setText("Title");

        lbTitleError.setForeground(new java.awt.Color(255, 0, 51));
        lbTitleError.setText("X");

        jLabel5.setText("Format date: yyyyMMdd");

        jLabel7.setText("Date");

        lbIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/default_image.png"))); // NOI18N

        lbPicturePathError.setForeground(new java.awt.Color(255, 0, 51));
        lbPicturePathError.setText("X");

        jScrollPane6.setViewportView(listActor);

        jScrollPane7.setViewportView(listDirector);

        jScrollPane8.setViewportView(listGenre);

        jScrollPane2.setViewportView(taDesc);

        jToolBarSelectedActorDirectorGenre.setBackground(new java.awt.Color(255, 255, 255));
        jToolBarSelectedActorDirectorGenre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jToolBarSelectedActorDirectorGenre.setRollover(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfPicturePath, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnChoose))
                    .addComponent(jScrollPane4)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfTitle))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                                    .addComponent(tfDate))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbDateError, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbDescError, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbTitleError, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jToolBarSelectedActorDirectorGenre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbPicturePathError, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbTitleError, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(3, 3, 3)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbDateError, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbDescError, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jScrollPane2))
                                .addGap(9, 9, 9))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jToolBarSelectedActorDirectorGenre, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfPicturePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnChoose)
                            .addComponent(lbPicturePathError, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnUpdate)
                            .addComponent(btnAdd)
                            .addComponent(btnDelete))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseActionPerformed
        File file = FileUtils.uploadFile("Images", "jpg", "jpeg", "png");
        if (file == null) {
            return;
        }
        tfPicturePath.setText(file.getAbsolutePath());
        setIcon(lbIcon, file);
    }//GEN-LAST:event_btnChooseActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        if (!formValid()) {
            return;
        }
        try {
            String picturePath = uploadImage();
            
            LocalDate date = LocalDate.parse(
                tfDate.getText().trim(),
                Movie.DATE_FORMATTER
            );
            
            Movie movie = new Movie(
                tfTitle.getText().trim(),
                picturePath,
                taDesc.getText().trim(),
                date
            );
            
            fetchToolBarsContentTags(movie);
            
            int idMovie = repository.createMovie(movie);
            
            movie.setId(idMovie);
            
            MovieModel.setMovies(repository.readMovies());

            for(Actor actor : movie.getActors()) repository.createActorFromMovie(movie.getId(), actor.getId());
            for(Director director : movie.getDirectors()) repository.createActorFromMovie(movie.getId(), director.getId());
            for(Genre genre : movie.getGenres()) repository.createActorFromMovie(movie.getId(), genre.getId());
            
            clearForm();
            
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null,"An unexpected error occurred!\n" + e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        if (selectedMovie == null) {
            MessageUtils.showInformationMessage("Info", "Plese select article");
            return;
        }
        if (!formValid()) {
            return;
        }
        try {
            // check if image has been changed
            if (!tfPicturePath.getText().trim().equals(
                selectedMovie.getPicturePath()
            )) {
                //delete an old image if it exists
                if (Files.exists(Paths.get(selectedMovie.getPicturePath()))) {
                    Files.deleteIfExists(Paths.get(selectedMovie.getPicturePath()));
                }
                // upload new image
                String picturePath = uploadImage();
                selectedMovie.setPicturePath(picturePath);
            }

            selectedMovie.setTitle(tfTitle.getText().trim());
            selectedMovie.setDescription(taDesc.getText().trim());
            selectedMovie.setPublishedDate(LocalDate.parse(
                tfDate.getText().trim(),
                Movie.DATE_FORMATTER
            ));
            
            updateMoviesRelationshipActor_Director_Genre();

            repository.updateMovie(selectedMovie.getId(), selectedMovie);

            MovieModel.setMovies(repository.readMovies());

            clearForm();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if (selectedMovie == null) {
            MessageUtils.showInformationMessage("Info", "Plese select article");
            return;
        }

        try {
            if (Files.exists(Paths.get(selectedMovie.getPicturePath()))) {
                Files.deleteIfExists(Paths.get(selectedMovie.getPicturePath()));
            }

            repository.deleteMovie(selectedMovie.getId());

            MovieModel.setMovies(repository.readMovies());

            clearForm();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tbMoviesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbMoviesMouseClicked
        selectMovie();
    }//GEN-LAST:event_tbMoviesMouseClicked

    private void tbMoviesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbMoviesKeyReleased
        selectMovie();
    }//GEN-LAST:event_tbMoviesKeyReleased


    private void initValidation() {
        validationFields = Arrays.asList(tfTitle,
                tfDate,
                taDesc,
                tfPicturePath
        );
        errorLabels = Arrays.asList(lbTitleError,
                lbDateError,
                lbDescError,
                lbPicturePathError,
                lbDateError
        );
    }

    private void hideErrors() {
        errorLabels.forEach(e -> e.setVisible(false));
    }

    private boolean formValid() {
        hideErrors();
        boolean ok = true;

        for (int i = 0; i < validationFields.size(); i++) {
            ok &= !validationFields.get(i).getText().trim().isEmpty();
            errorLabels.get(i).setVisible(validationFields.get(i).getText().trim().isEmpty());

            if ("DATE".equals(validationFields.get(i).getName())) {
                try {
                    LocalDate.parse(
                            validationFields.get(i).getText().trim(),
                            Movie.DATE_FORMATTER
                    );
                } catch (Exception e) {
                    ok = false;
                    errorLabels.get(i).setVisible(true);
                }
            }

        }
        return ok;
    }

    private void clearForm() {
        hideErrors();
        validationFields.forEach(e -> e.setText(""));
        lbIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/default_image.png")));
        selectedMovie = null;
        jToolBarSelectedActorDirectorGenre.removeAll();
        jToolBarSelectedActorDirectorGenre.revalidate();
        jToolBarSelectedActorDirectorGenre.repaint();
    }
    
    private void setIcon(JLabel label, File file) {
        try {
            label.setIcon(IconUtils.createIcon(file, label.getWidth(), label.getHeight()));
        } catch (IOException ex) {
            Logger.getLogger(UploadMovie.class.getName()).log(Level.SEVERE, null, ex);
            MessageUtils.showErrorMessage("Error", "Unable to set icon!");
        }
    }
    
    private void init() {
        try {
            initValidation();
            hideErrors();
            initRepository();
            initActorList();
            initGenreList();
            initDirectorList();
            initTable();
            initActorDirectorGenreToolBar();
        } catch (Exception ex) {
            Logger.getLogger(UploadMovie.class.getName()).log(Level.SEVERE, null, ex);
            MessageUtils.showErrorMessage("Unrecoverable error", "Cannot initiate the form");
            System.exit(1);
        }
    }
    
    private void initRepository() throws Exception {
        repository = RepoFactory.getRepository();
    }

    private void initTable() throws Exception {
        tbMovies.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tbMovies.setAutoCreateRowSorter(true);
        tbMovies.setRowHeight(25);
        MovieModel = new MovieTableModel(repository.readMovies());
        tbMovies.setModel(MovieModel);
    }

    private static final String DIR = "assets";

    private String uploadImage() throws IOException {
        String origPath = tfPicturePath.getText().trim();
        String ext = origPath.substring(origPath.lastIndexOf("."));
        String name = UUID.randomUUID().toString() + ext;
        String picturePath = DIR + File.separator + name;
        FileUtils.copyImage(origPath, picturePath);
        return picturePath;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnChoose;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JToolBar jToolBarSelectedActorDirectorGenre;
    private javax.swing.JLabel lbDateError;
    private javax.swing.JLabel lbDescError;
    private javax.swing.JLabel lbIcon;
    private javax.swing.JLabel lbPicturePathError;
    private javax.swing.JLabel lbTitleError;
    private javax.swing.JList<String> listActor;
    private javax.swing.JList<String> listDirector;
    private javax.swing.JList<String> listGenre;
    private javax.swing.JTextPane taDesc;
    private javax.swing.JTable tbMovies;
    private javax.swing.JTextField tfDate;
    private javax.swing.JTextField tfPicturePath;
    private javax.swing.JTextField tfTitle;
    // End of variables declaration//GEN-END:variables

    private void selectMovie() {
        int selectedRow = tbMovies.getSelectedRow();
        int rowIndex = tbMovies.convertRowIndexToModel(selectedRow);
        int id = (int) MovieModel.getValueAt(rowIndex, 0);
        try {
            Optional<Movie> opt = repository.readMovie(id);
            if (opt.isPresent()) {
                showMovie(opt.get());
                
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private void showMovie(Movie movie) {
        selectedMovie = movie;

        tfTitle.setText(selectedMovie.getTitle());
        tfDate.setText(selectedMovie.getPublishedDate().format(Movie.DATE_FORMATTER));
        taDesc.setText(selectedMovie.getDescription());
        tfPicturePath.setText(selectedMovie.getPicturePath());

        setIcon(lbIcon, new File(selectedMovie.getPicturePath()));
        try{
            
            jToolBarSelectedActorDirectorGenre.setTransferHandler(new MultiEntityTransferHandler(jToolBarSelectedActorDirectorGenre, repository.readActorsFromMovie(selectedMovie.getId()), repository.readDirectorsFromMovie(selectedMovie.getId()), repository.selectGenresFromMovie(selectedMovie.getId())));
            jToolBarSelectedActorDirectorGenre.revalidate(); // Refresh the layout
            jToolBarSelectedActorDirectorGenre.repaint();         
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void initActorList() throws Exception{
        listActor.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        ActorModel = new ActorListModel(repository.readActors());
        listActor.setModel(ActorModel);
        listActor.setDragEnabled(true);
        listActor.setTransferHandler(new ActorExportTransferHandler());
    }

    private void initGenreList() throws Exception{
        listGenre.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        GenreModel = new GenreListModel(repository.readGenres());
        listGenre.setModel(GenreModel);
        listGenre.setDragEnabled(true);
        listGenre.setTransferHandler(new GenreExportTransferHandler());
    }

    private void initDirectorList() throws Exception{
        listDirector.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        DirectorModel = new DirectorListModel(repository.readDirectors());
        listDirector.setModel(DirectorModel);
        listDirector.setDragEnabled(true);
        listDirector.setTransferHandler(new DirectorExportTransferHandler());
    }
    
    private void initActorDirectorGenreToolBar() throws Exception{
        jToolBarSelectedActorDirectorGenre.setTransferHandler(new MultiEntityTransferHandler(jToolBarSelectedActorDirectorGenre));     
        jToolBarSelectedActorDirectorGenre.setFloatable(false);
        jToolBarSelectedActorDirectorGenre.revalidate(); // Refresh the layout
        jToolBarSelectedActorDirectorGenre.repaint();
    }

    private void fetchToolBarsContentTags(Movie movie) {
        for (Component comp : jToolBarSelectedActorDirectorGenre.getComponents()) {
            if (comp instanceof JButton button) {
                if(button.getClientProperty("Actor") != null && button.getClientProperty("Actor") instanceof Actor){
                    movie.getActors().add((Actor) button.getClientProperty("Actor"));
                }
                if(button.getClientProperty("Director") != null && button.getClientProperty("Director") instanceof Director){
                    movie.getDirectors().add((Director) button.getClientProperty("Director"));
                }
                if(button.getClientProperty("Genre") != null && button.getClientProperty("Genre") instanceof Genre){
                    movie.getGenres().add((Genre) button.getClientProperty("Genre"));
                }
            }
        }
    }

    private void updateMoviesRelationshipActor_Director_Genre() throws Exception{
        fetchToolBarsContentTags(selectedMovie);
        
        if(!selectedMovie.getActors().isEmpty()){
            
            // Get current actors from database for this movie
            List<Actor> dbActors = repository.readActorsFromMovie(selectedMovie.getId());

            // Create sets for efficient comparison
            Set<Integer> selectedActorIds = selectedMovie.getActors().stream()
                    .map(Actor::getId)
                    .collect(Collectors.toSet());

            Set<Integer> dbActorIds = dbActors.stream()
                    .map(Actor::getId)
                    .collect(Collectors.toSet());

            // Delete relationships that exist in DB but not in selectedMovie
            for (Integer dbActorId : dbActorIds) {
                if (!selectedActorIds.contains(dbActorId)) {
                    repository.deleteActorFromMovie(selectedMovie.getId(), dbActorId);
                }
            }

            // Create relationships that exist in selectedMovie but not in DB
            for (Integer selectedActorId : selectedActorIds) {
                if (!dbActorIds.contains(selectedActorId)) {
                    repository.createActorFromMovie(selectedMovie.getId(), selectedActorId);
                }
            }
            
        }else{
            for(Actor actor : repository.readActorsFromMovie(selectedMovie.getId())){
                repository.deleteActorFromMovie(selectedMovie.getId(), actor.getId());
            }
        }
        // Directors synchronization
        if (!selectedMovie.getDirectors().isEmpty()) {
            // Get current directors from database for this movie
            List<Director> dbDirectors = repository.readDirectorsFromMovie(selectedMovie.getId());

            // Create sets for efficient comparison
            Set<Integer> selectedDirectorIds = selectedMovie.getDirectors().stream()
                    .map(Director::getId)
                    .collect(Collectors.toSet());

            Set<Integer> dbDirectorIds = dbDirectors.stream()
                    .map(Director::getId)
                    .collect(Collectors.toSet());

            // Delete relationships that exist in DB but not in selectedMovie
            for (Integer dbDirectorId : dbDirectorIds) {
                if (!selectedDirectorIds.contains(dbDirectorId)) {
                    repository.removeDirectorFromMovie(selectedMovie.getId(), dbDirectorId);
                }
            }

            // Create relationships that exist in selectedMovie but not in DB
            for (Integer selectedDirectorId : selectedDirectorIds) {
                if (!dbDirectorIds.contains(selectedDirectorId)) {
                    repository.createDirectorToMovie(selectedMovie.getId(), selectedDirectorId);
                }
            }

        } else {
            // If selectedMovie has no directors, delete all existing relationships
            for (Director director : repository.readDirectorsFromMovie(selectedMovie.getId())) {
                repository.removeDirectorFromMovie(selectedMovie.getId(), director.getId());
            }
        }

        // Genres synchronization
        if (!selectedMovie.getGenres().isEmpty()) {
            // Get current genres from database for this movie
            List<Genre> dbGenres = repository.selectGenresFromMovie(selectedMovie.getId());

            // Create sets for efficient comparison
            Set<Integer> selectedGenreIds = selectedMovie.getGenres().stream()
                    .map(Genre::getId)
                    .collect(Collectors.toSet());

            Set<Integer> dbGenreIds = dbGenres.stream()
                    .map(Genre::getId)
                    .collect(Collectors.toSet());

            // Delete relationships that exist in DB but not in selectedMovie
            for (Integer dbGenreId : dbGenreIds) {
                if (!selectedGenreIds.contains(dbGenreId)) {
                    repository.removeGenreFromMovie(selectedMovie.getId(), dbGenreId);
                }
            }

            // Create relationships that exist in selectedMovie but not in DB
            for (Integer selectedGenreId : selectedGenreIds) {
                if (!dbGenreIds.contains(selectedGenreId)) {
                    repository.createGenreToMovie(selectedMovie.getId(), selectedGenreId);
                }
            }

        } else {
            // If selectedMovie has no genres, delete all existing relationships
            for (Genre genre : repository.selectGenresFromMovie(selectedMovie.getId())) {
                repository.removeGenreFromMovie(selectedMovie.getId(), genre.getId());
            }
        }
    }
}
